In [1]:
import numpy as np

# 串列與Numpy array的差異

In [2]:
a = [10,15,20]

b = np.array([10,15,20])

print("串列的相乘:",a * 3)
print("Numpy的相乘:",b * 3)

串列的相乘: [10, 15, 20, 10, 15, 20, 10, 15, 20]
Numpy的相乘: [30 45 60]


# 建立ndarray

In [3]:
a = np.array([10,15,20])
print(a)
print(type(a))
print(a.dtype)

[10 15 20]
<class 'numpy.ndarray'>
int32


In [13]:
b = [10.,15,20]
b = np.array(b)
print(b)
print(type(b))
print(b.dtype)

[10. 15. 20.]
<class 'numpy.ndarray'>
float64


In [19]:
print(a)
print(a + 2)
print(a - 11)
print(a * 3)
print(a / 3)

[10 15 20]
[12 17 22]
[-1  4  9]
[30 45 60]
[3.33333333 5.         6.66666667]


In [21]:
a = np.array([10,15,20])
b = np.array([2,11,3])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[12 26 23]
[ 8  4 17]
[ 20 165  60]
[5.         1.36363636 6.66666667]


In [26]:
a = np.array([10,15,20])
b = np.array([2])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[12 17 22]
[ 8 13 18]
[20 30 40]
[ 5.   7.5 10. ]


# 建立一維陣列

In [30]:
a = np.array([1,2,3,4,5,6,7,8,9,0])

print(a)
print(a.shape)


[1 2 3 4 5 6 7 8 9 0]
(10,)


10

# 建立二維陣列

In [51]:
a = [
        [1,2,3,4,5,6],
        [2,3,4,5,6,7],
        [3,4,5,6,7,8],
        [4,5,6,7,8,9],
        [5,6,7,8,9,0],
    ]

print("串列的資料長度:",len(a))

a = np.array(a)
print("資料顯示:\n",a)
print("二維陣列的維度與資料長度:",a.shape)

串列的資料長度: 5
資料顯示:
 [[1 2 3 4 5 6]
 [2 3 4 5 6 7]
 [3 4 5 6 7 8]
 [4 5 6 7 8 9]
 [5 6 7 8 9 0]]
二維陣列的維度與資料長度: (5, 6)


In [72]:
a = [
        [1,2,3],
        [2,3,4,5,6,7],
        [3,4,5,6,7],
        [4,5,6,9],
        [5,6,7,8,9,0],
    ]

a = np.array(a)

print(a * 3)

[list([1, 2, 3, 1, 2, 3, 1, 2, 3])
 list([2, 3, 4, 5, 6, 7, 2, 3, 4, 5, 6, 7, 2, 3, 4, 5, 6, 7])
 list([3, 4, 5, 6, 7, 3, 4, 5, 6, 7, 3, 4, 5, 6, 7])
 list([4, 5, 6, 9, 4, 5, 6, 9, 4, 5, 6, 9])
 list([5, 6, 7, 8, 9, 0, 5, 6, 7, 8, 9, 0, 5, 6, 7, 8, 9, 0])]


# 建立三維陣列

In [73]:
a = [
        [1,2,3,4,5,6],
        [2,3,4,5,6,7],
        [3,4,5,6,7,8],
        [4,5,6,7,8,9],
        [5,6,7,8,9,0],
    ]
b = [a,a,a]
b = np.array(b)

print("資料顯示:\n",b)
print("三維陣列的維度與資料長度:",b.shape)

資料顯示:
 [[[1 2 3 4 5 6]
  [2 3 4 5 6 7]
  [3 4 5 6 7 8]
  [4 5 6 7 8 9]
  [5 6 7 8 9 0]]

 [[1 2 3 4 5 6]
  [2 3 4 5 6 7]
  [3 4 5 6 7 8]
  [4 5 6 7 8 9]
  [5 6 7 8 9 0]]

 [[1 2 3 4 5 6]
  [2 3 4 5 6 7]
  [3 4 5 6 7 8]
  [4 5 6 7 8 9]
  [5 6 7 8 9 0]]]
三維陣列的維度與資料長度: (3, 5, 6)


# ndim, shape屬性

In [5]:
a = [
        [1,2,3,4,5,6],
        [2,3,4,5,6,7],
        [3,4,5,6,7,8],
        [4,5,6,7,8,9],
        [5,6,7,8,9,0],
    ]
a = np.array(a)

print("ndim:",a.ndim)

ndim: 2


In [93]:
print("shape:",a.shape)

shape: (5, 6)


In [94]:
ndim = len(a.shape)
print("ndim:",ndim)

ndim: 2


# 串列(list)常與ndarray的屬性混淆

In [7]:
a = [
        [1,2,3,4,5,6],
        [2,3,4,5,6,7],
        [3,4,5,6,7,8],
        [4,5,6,7,8,9],
        [5,6,7,8,9,0],
    ]
print(a.shape)

AttributeError: 'list' object has no attribute 'shape'

In [12]:
a = [
        [1,2,3,4,5,6],
        [2,3,4,5,6,7],
    ]
print("串列a的長度:",len(a))

b = np.array(a)
print("ndarray b的長度:",len(b))
print("ndarray b的shape:",b.shape)

串列a的長度: 2
ndarray b的長度: 2
ndarray b的shape: (2, 6)


# 轉置陣列

In [97]:
a = [
        [1,2,3,4,5,6],
        [22,33,44,55,66,77]
    ]
a = np.array(a)

b = a.T

print("原始陣列shape:",a.shape)
print("轉置陣列shape:",b.shape )

原始陣列shape: (2, 6)
轉置陣列shape: (6, 2)


In [99]:
print(a)
print(b)

[[ 1  2  3  4  5  6]
 [22 33 44 55 66 77]]
[[ 1 22]
 [ 2 33]
 [ 3 44]
 [ 4 55]
 [ 5 66]
 [ 6 77]]


In [111]:
a = [
        [1,2,3,4,5],
        [12,13,14,15,16],
        [23,24,25,26,27],
        [34,35,36,37,38]
    ]

a = [a,a,a]
a = [a,a]
a = np.array(a)

print(a.shape)
print(a.T.shape)

(2, 3, 4, 5)
(5, 4, 3, 2)


In [109]:
print(a.T)

[[[ 1  1  1]
  [12 12 12]
  [23 23 23]
  [34 34 34]]

 [[ 2  2  2]
  [13 13 13]
  [24 24 24]
  [35 35 35]]

 [[ 3  3  3]
  [14 14 14]
  [25 25 25]
  [36 36 36]]

 [[ 4  4  4]
  [15 15 15]
  [26 26 26]
  [37 37 37]]

 [[ 5  5  5]
  [16 16 16]
  [27 27 27]
  [38 38 38]]]


# dtype屬性

In [112]:
a = np.array([10,15,20])
print(a.dtype)

int32


In [113]:
b = np.array([10.,15,20])
print(b.dtype)

float64


In [123]:
a = np.array([10,15,20],dtype='int16')

print(a.dtype)

int16


In [4]:
a = np.array([10,15,20],dtype=np.int16)

print(a.dtype)

int16


In [9]:
a = np.array([10.,15,20],dtype=int)

print(a.dtype)

int32


In [6]:
a = np.array([10,15,20],dtype=float)

print(a.dtype)

float64


In [133]:
a = np.array([128,15,20],dtype='int8')
print(a)

[-128   15   20]


In [134]:
b = np.array([128,15,20],dtype='uint8')
print(b)

[128  15  20]


In [23]:
a = np.array([-2.1,-1,0,1,1983],dtype=np.bool)

print(a)

[ True  True False  True  True]


# size屬性 

In [14]:
a = [
        [1,2,3,4,5,6],
        [2,3,4,5,6,7],
        [3,4,5,6,7,8],
        [4,5,6,7,8,9],
        [5,6,7,8,9,0],
    ]
a = np.array(a)

print("size:",a.size)

size: 30


In [13]:
shape = a.shape
print("shape:",shape)
size = shape[0] * shape[1]
print("size:",size)

shape: (5, 6)
size: 30


# 屬性itemsize

In [16]:
a = np.array([10,15,20],dtype=np.int16)

print("itemsize:",a.itemsize)
print("dtype:",a.dtype)


itemsize: 2
dtype: int16


# 屬性nbytes

In [19]:
a = [
        [1,2,3,4,5,6],
        [2,3,4,5,6,7],
        [3,4,5,6,7,8],
        [4,5,6,7,8,9],
        [5,6,7,8,9,0],
    ]
a = np.array(a)

print("nbytes:",a.nbytes)

nbytes: 120


In [20]:
print("size:",a.size)
print("itemsize:",a.itemsize)
print("nbytes:",a.size * a.itemsize)

size: 30
itemsize: 4
nbytes: 120


# 方法flatten()

In [31]:
a = [
        [1,2,3],
        [4,5,6],
        [7,8,9],
    ]
a = np.array(a)

print("原始陣列shape:",a.shape)
print("陣列內容:\n",a)

原始陣列shape: (3, 3)
陣列內容:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
b = a.flatten()
print("轉換至一維陣列shape:",b.shape)
print("陣列內容:\n",b)

轉換至一維陣列shape: (9,)
陣列內容:
 [1 2 3 4 5 6 7 8 9]


In [31]:
a = [
        [1,2,3],
        [4,5,6],
        [7,8,9],
    ]
b = [
        [11,12,13],
        [14,15,16],
        [17,18,19],
    ]
a = np.array([a,b])

print("原始陣列shape:",a.shape)
print("陣列內容:\n",a)

原始陣列shape: (2, 3, 3)
陣列內容:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]


In [32]:
b = a.flatten()
print("轉換至一維陣列shape:",b.shape)
print("陣列內容:\n",b)

轉換至一維陣列shape: (18,)
陣列內容:
 [ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]


# 方法reshape()

In [38]:
a = np.array([1,2,3,4,5,6,7,8,9,0])
print(a)

[1 2 3 4 5 6 7 8 9 0]


In [39]:
reshape = a.reshape((2,5))
print(reshape)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [43]:
reshape = a.reshape((1,5,2))
print(reshape)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]
  [9 0]]]


In [40]:
reshape = a.reshape((2,6))
print(reshape)

ValueError: cannot reshape array of size 10 into shape (2,6)

In [47]:
a = [
        [1,2,3],
        [4,5,6],
        [7,8,9],
    ]
b = [
        [11,12,13],
        [14,15,16],
        [17,18,19],
    ]
a = np.array([a,b])

print("原始陣列shape:",a.shape)
print("陣列內容:\n",a)

原始陣列shape: (2, 3, 3)
陣列內容:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]


In [52]:
b = a.flatten()
print("使用方法flatten:",b)

c = a.reshape((-1))
print("使用方法reshape((-1)):",c)

使用方法flatten: [ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
使用方法reshape((-1)): [ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]


# 方法astype()

In [5]:
a = np.array([10,15,20],dtype='int16')

print("宣告時的數值型態:",a.dtype)

a = a.astype(np.float32)

print("更改後的數值型態:",a.dtype)

宣告時的數值型態: int16
更改後的數值型態: float32


# np.expand_dim()

# np.sum()函數

### 一維的計算

In [77]:
a = np.array([1,2,3,4,5])

sum_no_axis = np.sum(a)#不考慮維度的計算
print("sum_no_axis:",sum_no_axis)

sum_no_axis: 15


In [78]:
print("shape:",a.shape)
sum_axis_0 = np.sum(a,axis=0)
print("sum_axis_0:",sum_axis_0)

shape: (5,)
sum_axis_0: 15


### 二維的計算

In [82]:
a = np.array([[1,2,3,4,5],
             [2,3,4,5,6],
             [3,4,5,6,7]])

sum_no_axis = np.sum(a)
print("sum_no_axis:",sum_no_axis)
a

sum_no_axis: 60


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [80]:
print("shape:",a.shape)
sum_axis_0 = np.sum(a,axis=0)
print("sum_axis_0:",sum_axis_0)

shape: (3, 5)
sum_axis_0: [ 6  9 12 15 18]


In [81]:
sum_axis_1 = np.sum(a,axis=1)
print("sum_axis_1:",sum_axis_1)

sum_axis_1: [15 20 25]


### 三維的計算

In [88]:
a = [
        [1,2,3,4],
        [4,5,6,7],
        [7,8,9,0],
    ]
b = [
        [11,12,13,14],
        [14,15,16,17],
        [17,18,19,20],
    ]
a = np.array([a,b])

sum_no_axis = np.sum(a)
print("sum_no_axis:",sum_no_axis)

sum_no_axis: 242


In [87]:
print("原始陣列shape:",a.shape)
print("陣列內容:\n",a)

原始陣列shape: (2, 3, 4)
陣列內容:
 [[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 7  8  9  0]]

 [[11 12 13 14]
  [14 15 16 17]
  [17 18 19 20]]]


In [91]:
print("shape:",a.shape)
sum_axis_0 = np.sum(a,axis=0)
print("sum_axis_0:\n",sum_axis_0)

shape: (2, 3, 4)
sum_axis_0:
 [[12 14 16 18]
 [18 20 22 24]
 [24 26 28 20]]


In [92]:
sum_axis_1 = np.sum(a,axis=1)
print("sum_axis_1:\n",sum_axis_1)

sum_axis_1:
 [[12 15 18 11]
 [42 45 48 51]]


In [94]:
sum_axis_2 = np.sum(a,axis=2)
print("sum_axis_2:\n",sum_axis_2)

sum_axis_2:
 [[10 22 24]
 [50 62 74]]


In [66]:
sum_axis_0 = np.sum(a,axis=0)
sum_axis_1 = np.sum(a,axis=1)
sum_axis_2 = np.sum(a,axis=2)
print(a)
print(a.shape)
print(sum_axis_0.shape)
print(sum_axis_1.shape)
print(sum_axis_2.shape)
print(sum_axis_1)
print(sum_axis_2)

[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 7  8  9  0]]

 [[11 12 13 14]
  [14 15 16 17]
  [17 18 19 20]]]
(2, 3, 4)
(3, 4)
(2, 4)
(2, 3)
[[12 15 18 11]
 [42 45 48 51]]
[[10 22 24]
 [50 62 74]]


# np.mean()函數

# 一維的計算

In [7]:
a = [1,2,3,4,5]

mean_no_axis = np.mean(a)#不考慮維度的計算
print("mean_no_axis:",mean_no_axis)

mean_no_axis: 3.0


# 二維的計算

In [11]:
a =[[1,2,3,4,5],
     [2,3,4,5,6],
     [3,4,5,6,7]]

mean_no_axis = np.mean(a)
print("mean_no_axis:",mean_no_axis)

mean_axis_0 = np.mean(a,axis=0)
print("mean_axis_0:",mean_axis_0)

mean_axis_1 = np.mean(a,axis=1)
print("mean_axis_1:",mean_axis_1)

mean_no_axis: 4.0
mean_axis_0: [2. 3. 4. 5. 6.]
mean_axis_1: [3. 4. 5.]


# 範例:多位學生成績的計算

In [18]:
Jay = [92.5,62,77]
Rebecca = [88,93,81]
Yuna = [82,83,84]
score_list = [Jay,Rebecca,Yuna]
print("score_list:",score_list)

sum_axis_1 = np.sum(score_list,axis=1)
mean_axis_1 = np.mean(score_list,axis=1)

for i,score in enumerate(score_list):
    print("分數:",score)
    print("總和:",sum_axis_1[i])
    print("平均:",mean_axis_1[i])

score_list: [[92.5, 62, 77], [88, 93, 81], [82, 83, 84]]
分數: [92.5, 62, 77]
總和: 231.5
平均: 77.16666666666667
分數: [88, 93, 81]
總和: 262.0
平均: 87.33333333333333
分數: [82, 83, 84]
總和: 249.0
平均: 83.0


# 三維的計算

In [26]:
a = [
        [1,2,3,4],
        [4,5,6,7],
        [7,8,9,0],
    ]
b = [
        [11,12,13,14],
        [14,15,16,17],
        [17,18,19,20],
    ]
a = np.array([a,b])

mean_no_axis = np.mean(a)
print("mean_no_axis:",mean_no_axis)

mean_no_axis: 10.083333333333334


In [23]:
mean_axis_0 = np.mean(a,axis=0)
print("mean_axis_0:\n",mean_axis_0)

mean_axis_0:
 [[ 6.  7.  8.  9.]
 [ 9. 10. 11. 12.]
 [12. 13. 14. 10.]]


In [24]:
mean_axis_1 = np.mean(a,axis=1)
print("mean_axis_1:\n",mean_axis_1)

mean_axis_1:
 [[ 4.          5.          6.          3.66666667]
 [14.         15.         16.         17.        ]]


In [22]:
mean_axis_2 = np.mean(a,axis=2)
print("mean_axis_2:\n",mean_axis_2)

mean_axis_2:
 [[ 2.5  5.5  6. ]
 [12.5 15.5 18.5]]


# np.average()函數

In [2]:
Jay = [92.5,62,77]
Rebecca = [88,93,81]
Yuna = [82,83,84]
score_list = [Jay,Rebecca,Yuna]

#----使用np.mean()函數
print(np.mean(score_list,axis=1))

#----使用np.average()函數
print(np.average(score_list,axis=1))

[77.16666667 87.33333333 83.        ]
[77.16666667 87.33333333 83.        ]


# np.max()函數與np.min()函數

# 一維的計算

In [13]:
a = [1,2,3,4,5]

max_no_axis = np.max(a)#不考慮維度的計算
print("max_no_axis:",max_no_axis)

min_no_axis = np.min(a)#不考慮維度的計算
print("min_no_axis:",min_no_axis)

max_no_axis: 5
min_no_axis: 1


# 二維的計算

In [18]:
a =[[1,2,3,4,5],
     [2,3,4,5,6],
     [3,4,5,6,7]]

max_no_axis = np.max(a)
print("max_no_axis:",max_no_axis)
min_no_axis = np.min(a)
print("min_no_axis:",min_no_axis)

max_axis_0 = np.max(a,axis=0)
print("max_axis_0:",max_axis_0)
min_axis_0 = np.min(a,axis=0)
print("min_axis_0:",min_axis_0)

max_axis_1 = np.max(a,axis=1)
print("max_axis_1:",max_axis_1)
min_axis_1 = np.min(a,axis=1)
print("min_axis_1:",min_axis_1)

max_no_axis: 7
min_no_axis: 1
max_axis_0: [3 4 5 6 7]
min_axis_0: [1 2 3 4 5]
max_axis_1: [5 6 7]
min_axis_1: [1 2 3]


# 範例:多位學生成績的計算(加入最大最小值)

In [19]:
Jay = [92.5,62,77]
Rebecca = [88,93,81]
Yuna = [82,83,84]
score_list = [Jay,Rebecca,Yuna]
print("score_list:",score_list)

sum_axis_1 = np.sum(score_list,axis=1)
mean_axis_1 = np.mean(score_list,axis=1)
max_axis_1 = np.max(score_list,axis=1)
min_axis_1 = np.min(score_list,axis=1)

for i,score in enumerate(score_list):
    print("分數:",score)
    print("總和:",sum_axis_1[i])
    print("平均:",mean_axis_1[i])
    print("最高分:",max_axis_1[i])
    print("最低分:",min_axis_1[i])

score_list: [[92.5, 62, 77], [88, 93, 81], [82, 83, 84]]
分數: [92.5, 62, 77]
總和: 231.5
平均: 77.16666666666667
最高分: 92.5
最低分: 62.0
分數: [88, 93, 81]
總和: 262.0
平均: 87.33333333333333
最高分: 93.0
最低分: 81.0
分數: [82, 83, 84]
總和: 249.0
平均: 83.0
最高分: 84.0
最低分: 82.0


# 三維的計算

In [21]:
a = [
        [1,2,3,4],
        [4,5,6,7],
        [7,8,9,0],
    ]
b = [
        [11,12,13,14],
        [14,15,16,17],
        [17,18,19,20],
    ]
a = np.array([a,b])

max_no_axis = np.max(a)
print("max_no_axis:",max_no_axis)
min_no_axis = np.min(a)
print("min_no_axis:",min_no_axis)

max_no_axis: 20
min_no_axis: 0


In [23]:
max_axis_0 = np.max(a,axis=0)
print("max_axis_0:\n",max_axis_0)
min_axis_0 = np.min(a,axis=0)
print("min_axis_0:\n",min_axis_0)

max_axis_0:
 [[11 12 13 14]
 [14 15 16 17]
 [17 18 19 20]]
min_axis_0:
 [[1 2 3 4]
 [4 5 6 7]
 [7 8 9 0]]


In [25]:
max_axis_1 = np.max(a,axis=1)
print("max_axis_1:\n",max_axis_1)
min_axis_1 = np.min(a,axis=1)
print("min_axis_1:\n",min_axis_1)

max_axis_1:
 [[ 7  8  9  7]
 [17 18 19 20]]
min_axis_1:
 [[ 1  2  3  0]
 [11 12 13 14]]


In [27]:
max_axis_2 = np.max(a,axis=2)
print("max_axis_2:\n",max_axis_2)
min_axis_2 = np.min(a,axis=2)
print("min_axis_2:\n",min_axis_2)
print(np.argmax(a))

max_axis_2:
 [[ 4  7  9]
 [14 17 20]]
min_axis_2:
 [[ 1  4  0]
 [11 14 17]]
23


# np.argmax()函數與np.argmin()函數

# 一維陣列的計算

In [32]:
a = [1,2,3,4,5]

argmax_no_axis = np.argmax(a)
print("陣列a最大值的索引值 = ",argmax_no_axis)
print("陣列a最大值 = ",a[argmax_no_axis])

argmin_no_axis = np.argmin(a)
print("陣列a最小值的索引值 = :",argmin_no_axis)
print("陣列a最大值 = ",a[min_no_axis])

陣列a最大值的索引值 =  4
陣列a最大值 =  5
陣列a最小值的索引值 = : 0
陣列a最大值 =  1


# 二維陣列的計算

In [7]:
a =[[3,2, 5,4,1],
    [2,33,4,5,6],
    [3,4, 5,6,7]]

argmax_no_axis = np.argmax(a)
print("陣列a最大值的索引值 = ",argmax_no_axis)

a = np.array(a)
print("陣列拉直(flatten):",a.flatten())
print("陣列a最大值 = ",a.flatten()[argmax_no_axis])

陣列a最大值的索引值 =  6
陣列拉直(flatten): [ 3  2  5  4  1  2 33  4  5  6  3  4  5  6  7]
陣列a最大值 =  33


In [41]:
argmin_no_axis = np.argmin(a)
print("陣列a最小值的索引值 = ",argmin_no_axis)
print("陣列a最大值 = ",a.flatten()[argmin_no_axis])

陣列a最小值的索引值 =  4
陣列a最大值 =  1


In [8]:
argmax_axis_0 = np.argmax(a,axis=0)
print("argmax_axis_0:\n",argmax_axis_0)

argmax_axis_0:
 [0 1 0 2 2]


In [9]:
argmin_axis_0 = np.argmin(a,axis=0)
print("argmin_axis_0:\n",argmin_axis_0)

argmin_axis_0:
 [1 0 1 0 0]


In [10]:
argmax_axis_1 = np.argmax(a,axis=1)
print("argmax_axis_1:\n",argmax_axis_1)

argmax_axis_1:
 [2 1 4]


In [11]:
argmin_axis_1 = np.argmin(a,axis=1)
print("argmin_axis_1:\n",argmin_axis_1)

argmin_axis_1:
 [4 0 0]


In [15]:
Jay = [92.5,62,77]
Rebecca = [88,93,81]
Yuna = [82,83,84]
score_list = [Jay,Rebecca,Yuna]
print("score_list:",score_list)

sum_axis_1 = np.sum(score_list,axis=1)
mean_axis_1 = np.mean(score_list,axis=1)
argmax_axis_1 = np.argmax(score_list,axis=1)
argmin_axis_1 = np.argmin(score_list,axis=1)

for i,score in enumerate(score_list):
    print("分數:",score)
    print("總和:",sum_axis_1[i])
    print("平均:",mean_axis_1[i])
    print("最高分:",score[argmax_axis_1[i]])
    print("最低分:",score[argmin_axis_1[i]])

score_list: [[92.5, 62, 77], [88, 93, 81], [82, 83, 84]]
分數: [92.5, 62, 77]
總和: 231.5
平均: 77.16666666666667
最高分: 92.5
最低分: 62
分數: [88, 93, 81]
總和: 262.0
平均: 87.33333333333333
最高分: 93
最低分: 81
分數: [82, 83, 84]
總和: 249.0
平均: 83.0
最高分: 84
最低分: 82


In [18]:
names = ['Stephen Curry','LeBron James','Kevin Durant']
height = [190,206,208]
weight = [83,113,108]
points = [32,25,26.9]
argmax = np.argmax(points)

print("2020-2021平均得分最高的是:",names[argmax])
print("身高:",height[argmax])
print("體重:",weight[argmax])
print("得分:",points[argmax])

2020-2021平均得分最高的是: Stephen Curry
身高: 190
體重: 83
得分: 32


In [19]:
names = ['Stephen Curry','LeBron James','Kevin Durant']
height = [190,206,208]
weight = [83,113,108]
points = [32,25,26.9]
argmax = np.argmax(height)

print("身高最高的是:",names[argmax])
print("身高:",height[argmax])
print("體重:",weight[argmax])
print("得分:",points[argmax])

身高最高的是: Kevin Durant
身高: 208
體重: 108
得分: 26.9


# np.zeros()函數

In [2]:
a = np.zeros(10)#建立一維，資料長度=10的陣列
print(a)
print(a.shape)
print(a.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)
float64


In [3]:
#建立二維，資料長度(3,5)的陣列
a = np.zeros((3,5),dtype=np.uint8)#自行設定數值形態
print(a)
print(a.shape)
print(a.dtype)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
(3, 5)
uint8


# np.zeros_like()函數

In [5]:
a = [[1,2,3],[4,5,6]]
b = np.zeros_like(a)

print(b)
print(b.shape)
print(b.dtype)

[[0 0 0]
 [0 0 0]]
(2, 3)
int32


# np.ones()函數

In [7]:
a = np.ones(10)#建立一維，資料長度=10的陣列
print(a)
print(a.shape)
print(a.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
(10,)
float64


In [8]:
#建立二維，資料長度(3,5)的陣列
a = np.ones((3,5),dtype=np.int8)#自行設定數值形態
print(a)
print(a.shape)
print(a.dtype)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
(3, 5)
int8


In [9]:
a = np.ones((2,5),dtype=np.uint8)
a *= 255
print(a)
print(a.shape)
print(a.dtype)

[[255 255 255 255 255]
 [255 255 255 255 255]]
(2, 5)
uint8


# np.ones_like()函數

In [10]:
a = [[1,2,3],[4,5,6]]
b = np.ones_like(a)

print(b)
print(b.shape)
print(b.dtype)

[[1 1 1]
 [1 1 1]]
(2, 3)
int32


# np.add()函數

In [26]:
a = [1,2,3,4,5]
b = [2,3,4,5,6]

#----方式1:轉換成ndarray
a = np.array(a)
b = np.array(b)

add = a + b
print("add = ",add)
print('add dtype = ',add.dtype)

add =  [ 3  5  7  9 11]
add dtype =  int32


In [25]:
a = [1,2,3,4,5]
b = [2,3,4,5,6]

#----方式2:使用np.add()函數
add = np.add(a,b)
print("add = ",add)
print('add dtype = ',add.dtype)

add =  [ 3  5  7  9 11]
add dtype =  int32


In [27]:
a = [1,2,3,4,5]
b = [2,3.,4,5,6]

add = np.add(a,b)
print("add = ",add)
print('add dtype = ',add.dtype)

add =  [ 3.  5.  7.  9. 11.]
add dtype =  float64


In [22]:
a = np.array([[1,2,3,4,5],
             [2,3,4,5,6],
             [3,4,5,6,7]])
b = 1#純量
add = np.add(a,b)
print("add = ",add)
print('add dtype = ',add.dtype)

add =  [[2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
add dtype =  int32


In [23]:
a = np.array([[1,2,3,4,5],
             [2,3,4,5,6],
             [3,4,5,6,7]])

b = [1]#一維且資料長度=1的陣列
add = np.add(a,b)
print("add = ",add)
print('add dtype = ',add.dtype)

add =  [[2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
add dtype =  int32


In [30]:
a = [1,2,3,4,5]
b = [2,3,4,5,6]

#----方式2:使用np.add()函數
add = np.multiply(a,b)
print("add = ",add)
print('add dtype = ',add.dtype)

add =  [ 2  6 12 20 30]
add dtype =  int32


In [4]:
np.max([1,2,3,99,5])
np.argmax([1,2,3,99,5])

3

# np.random.randint()

In [54]:
print(np.random.randint(0,100))

76


In [58]:
num_list = np.random.randint(0,100,16)
print(num_list)
print(num_list.dtype)
print(type(num_list))

[ 6 25 64  6 39 37  8 60 31 98 65 54 22 41 21 85]
int32
<class 'numpy.ndarray'>


In [59]:
from numpy import random as np_rdm
import random as rdm

num = rdm.randint(0,100)
print(num)

num_list = np_rdm.randint(0.56,100.2,16)
print(num_list)

95
[73 72 27 45 97 88 63 97 46 98 59 88 35  6 70 41]


# np.random.permutation

In [65]:
names = ['Stephen Curry','LeBron James','Kevin Durant']
height = [190,206,208]
weight = [83,113,108]
points = [32,25,26.9]

indice = np.random.permutation(len(names))
print("排列順序:",indice)
#----串列轉換成ndarray
names = np.array(names)
height = np.array(height)
weight = np.array(weight)
points = np.array(points)
#----使用索引值列表重新排列
names = names[indice]
height = height[indice]
weight = weight[indice]
points = points[indice]
print(names)
print(height)
print(weight)
print(points)

排列順序: [2 1 0]
['Kevin Durant' 'LeBron James' 'Stephen Curry']
[208 206 190]
[108 113  83]
[26.9 25.  32. ]
