# 匯入Tensorflow套件

In [8]:
import tensorflow
if tensorflow.__version__.startswith('1.'):
    import tensorflow as tf
    from tensorflow.python.platform import gfile
else:
    import tensorflow as v2
    import tensorflow.compat.v1 as tf
    tf.disable_v2_behavior()
    import tensorflow.compat.v1.gfile as gfile
print("Tensorflow version:{}".format(tf.__version__))

Tensorflow version:2.5.0


In [9]:
num_sum = tf.add(5,6)
print("num_sum:",num_sum)

num_sum: Tensor("Add_1:0", shape=(), dtype=int32)


In [10]:
import numpy as np
num_sum = np.add(5,6)
print("num_sum:",num_sum)

num_sum: 11


In [36]:
num_sum = tf.add(5,6)
print("num_sum:",num_sum)

with tf.Session() as sess:
    print("num_sum:",sess.run(num_sum))

num_sum: Tensor("Add_2:0", shape=(), dtype=int32)
num_sum: 11


In [11]:
node_a = tf.add(5,6,name='node_a')
node_b = tf.multiply(node_a,3,name='node_b')
node_c = tf.subtract(node_b,3,name='node_c')

print("node_c = ",node_c)

node_c =  Tensor("node_c_1:0", shape=(), dtype=int32)


In [12]:
with tf.Session() as sess:
    print("node_c = ",sess.run(node_c))

node_c =  30


In [13]:
sess = tf.Session()
print("node_c = ",sess.run(node_c))
sess.close()

node_c =  30


# 常數tf.constant()的使用

In [14]:
a = tf.constant(61, dtype=tf.float32, name='constant_a')

b = tf.constant(61., name='constant_b')

print(a)
print(b)

Tensor("constant_a:0", shape=(), dtype=float32)
Tensor("constant_b:0", shape=(), dtype=float32)


In [15]:
with tf.Session() as sess:
    print("a = ",sess.run(a))
    print("b = ",sess.run(b))

a =  61.0
b =  61.0


In [16]:
c = tf.constant(61, shape=[3,3],dtype=tf.float32, name='constant_c')
print(c)

Tensor("constant_c:0", shape=(3, 3), dtype=float32)


In [17]:
with tf.Session() as sess:
    print("c = \n",sess.run(c))

c = 
 [[61. 61. 61.]
 [61. 61. 61.]
 [61. 61. 61.]]


In [18]:
d = tf.constant([[1,2],[3,4]], name='constant_d')
e = tf.constant([[1,2.],[3,4]], name='constant_e')
print(d)
print(e)

Tensor("constant_d:0", shape=(2, 2), dtype=int32)
Tensor("constant_e:0", shape=(2, 2), dtype=float32)


In [19]:
with tf.Session() as sess:
    print("d = \n",sess.run(d))
    print("e = \n",sess.run(e))

d = 
 [[1 2]
 [3 4]]
e = 
 [[1. 2.]
 [3. 4.]]


In [20]:
d = tf.constant([[1,2],[3,4]])
e = tf.constant([[1,2.],[3,4]])
print(d)
print(e)

Tensor("Const:0", shape=(2, 2), dtype=int32)
Tensor("Const_1:0", shape=(2, 2), dtype=float32)


# 衝突範例

In [21]:
d = tf.constant([[1,2.],[3,4]],dtype=tf.int32)
print(d)

TypeError: Expected int32, got 2.0 of type 'float' instead.

# 變數tf.Variable()用法

In [22]:
#----方式1:直接設定數值內容
a_0D=tf.Variable(1.,name='0D_Tensor')#0維的Tensor
print('a_0D',a_0D)

a_0D <tf.Variable '0D_Tensor:0' shape=() dtype=float32_ref>


In [23]:
a_1D=tf.Variable([1,2,3,4],name='1D_Tensor')#1維的Tensor
print('a_1D',a_1D)

a_1D <tf.Variable '1D_Tensor:0' shape=(4,) dtype=int32_ref>


In [24]:
a_2D=tf.Variable([[1,2],[3,4]],name='2D_Tensor')#2維的Tensor
print('a_2D',a_2D)

a_2D <tf.Variable '2D_Tensor:0' shape=(2, 2) dtype=int32_ref>


In [25]:
a_3D=tf.Variable([[[1,2],[3,4]]],name='3D_Tensor')#3維的Tensor
print('a_3D',a_3D)

a_3D <tf.Variable '3D_Tensor:0' shape=(1, 2, 2) dtype=int32_ref>


In [26]:
with tf.Session() as sess:
    
    sess.run(tf.global_variables_initializer())
    
    print(sess.run(a_0D))
    print(sess.run(a_1D))
    print(sess.run(a_2D))
    print(sess.run(a_3D))
  

1.0
[1 2 3 4]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]]


In [27]:
#----方式2: 
#搭配 tf.constant()、tf.ones()、tf.zeros()來建立tf.Variable()

ones = tf.ones(shape=[3,3],name='ones')
print("ones:",ones)#預設數值型態(dtype)float32

zeros = tf.zeros(shape=[3,3],name='zeros')
print("zeros:",zeros)#預設數值型態(dtype)float32

b=tf.Variable(tf.constant([[1,2],[1,2]]),name='b')
print("b: ",b)

c=tf.Variable(ones,name='c')
print("c: ",c)

d=tf.Variable(zeros,name='d')
print("d: ",d)

ones: Tensor("ones:0", shape=(3, 3), dtype=float32)
zeros: Tensor("zeros:0", shape=(3, 3), dtype=float32)
b:  <tf.Variable 'b:0' shape=(2, 2) dtype=int32_ref>
c:  <tf.Variable 'c:0' shape=(3, 3) dtype=float32_ref>
d:  <tf.Variable 'd:0' shape=(3, 3) dtype=float32_ref>


In [28]:
with tf.Session() as sess:
    
    sess.run(tf.global_variables_initializer())
    print("ones: \n",sess.run(ones))
    print("zeros: \n",sess.run(zeros))
    print('b: \n',sess.run(b))
    print('c: \n',sess.run(c))
    print('d: \n',sess.run(d))

ones: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
zeros: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
b: 
 [[1 2]
 [1 2]]
c: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
d: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
#----方式3: 
#搭配 tf.random函數來建立 tf.Variable() 

#tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
e=tf.Variable(tf.random_normal(shape=[3,3],mean=1.0,stddev=0.1),name='e')
print("e: ",e)

#tf.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
#所有的數值會落在|2*std_dev|區間,在區間外的數值會被去除，所以稱為被截斷的(truncated)
#tf.random_normal()則會包含所有數值
f=tf.Variable(tf.truncated_normal(shape=[3,3],mean=1.0,stddev=0.1),name='f')
print("f: ",f)

#tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)
#所有的數值會平均落在[minval, maxval區間 
g=tf.Variable(tf.random_uniform(shape=[3,3],minval=0.8,maxval=1.2),name='g')
print("g: ",g)

with tf.Session() as sess:
    
    sess.run(tf.global_variables_initializer())
    
    print('e: \n',sess.run(e))
    print('f: \n',sess.run(f))
    print('g: \n',sess.run(g))

e:  <tf.Variable 'e:0' shape=(3, 3) dtype=float32_ref>
f:  <tf.Variable 'f:0' shape=(3, 3) dtype=float32_ref>
g:  <tf.Variable 'g:0' shape=(3, 3) dtype=float32_ref>
e: 
 [[1.0756657  1.1131315  1.0916035 ]
 [1.043614   0.94494075 0.9794925 ]
 [0.97873986 0.90285957 0.80597824]]
f: 
 [[0.9437075  1.0743661  0.95120555]
 [0.88364357 1.0353849  0.9917112 ]
 [0.9898488  0.9485826  0.97107315]]
g: 
 [[1.1535685  0.9914816  0.8001799 ]
 [0.9727666  0.9327952  0.86764693]
 [1.0218061  1.0958776  1.0884562 ]]


# tf.placeholder()的用法

In [30]:
width = tf.placeholder('int32',name='width')
height = tf.placeholder('int32',name='height')

area = tf.multiply(width,height,name='area')

with tf.Session() as sess:
    
    sess.run(tf.global_variables_initializer())
    
    print("area = ",sess.run(area,feed_dict={width:8,height:7}))

area =  56


# tf.Graph()

In [31]:
graph = tf.Graph()#宣告計算圖
with graph.as_default():
    
    width = tf.placeholder('int32',name='width')
    height = tf.placeholder('int32',name='height')

    area = tf.multiply(width,height,name='area')

    with tf.Session() as sess:

        sess.run(tf.global_variables_initializer())

        print("area = ",sess.run(area,feed_dict={width:8,height:7}))


area =  56


In [32]:
width = tf.placeholder('int32',name='width')
width_2 = tf.placeholder('int32',name='width')
print(width)
print(width_2)

Tensor("width_1:0", dtype=int32)
Tensor("width_2:0", dtype=int32)


# 使用多個計算圖

In [33]:
Graph_1=tf.Graph()
with Graph_1.as_default():
    
    c1=tf.constant(1,name='c1')
    
    print("c1:",c1)
    
Graph_2=tf.Graph()
with Graph_2.as_default():
    
    c2=tf.constant(2,name='c1')
    
    print("c2:",c2)


with tf.Session(graph=Graph_1) as sess:
    
    sess.run(tf.global_variables_initializer())
    
    print('c1=',sess.run(c1))
    
with tf.Session(graph=Graph_2) as sess:
    
    sess.run(tf.global_variables_initializer())
    
    print('c2=',sess.run(c2))


c1: Tensor("c1:0", shape=(), dtype=int32)
c2: Tensor("c1:0", shape=(), dtype=int32)
c1= 1
c2= 2


In [34]:
Graph_1 = tf.Graph()
with Graph_1.as_default():
    height_1 = tf.placeholder(dtype=tf.float32,name='height')
    width_1 = tf.placeholder(dtype=tf.float32,name='width')
    area_1 = tf.multiply(height_1,width_1,name='area')
    
    print("area_1:",area_1)
    
    sess_1 = tf.Session(graph=Graph_1)
    sess_1.run(tf.global_variables_initializer())


Graph_2 = tf.Graph()
with Graph_2.as_default():
    height_2 = tf.placeholder(dtype=tf.float32,name='height')
    width_2 = tf.placeholder(dtype=tf.float32,name='width')
    area_2 = tf.multiply(height_2,width_2)
    area_2 = tf.divide(area_2,1000.,name='area')
    
    print("area_2:",area_2)
    
    sess_2 = tf.Session()
    sess_2.run(tf.global_variables_initializer())
    
print("area_1:",sess_1.run(area_1,feed_dict={height_1:100.,width_1:100.}))
print("area_2:",sess_2.run(area_2,feed_dict={height_2:100.,width_2:100.}))  

sess_1.close()
sess_2.close()

area_1: Tensor("area:0", dtype=float32)
area_2: Tensor("area:0", dtype=float32)
area_1: 10000.0
area_2: 10.0


# GPU資源設定

In [35]:
GPU_ratio = None

Graph_1 = tf.Graph()
with Graph_1.as_default():
    height_1 = tf.placeholder(dtype=tf.float32,name='height')
    width_1 = tf.placeholder(dtype=tf.float32,name='width')
    area_1 = tf.multiply(height_1,width_1,name='area')
    
    print("area_1:",area_1)
    
    #----GPU setting
    config = tf.ConfigProto(log_device_placement=True,
                            allow_soft_placement=True)
    if GPU_ratio is None:
        config.gpu_options.allow_growth = True
    else:
        config.gpu_options.per_process_gpu_memory_fraction = GPU_ratio
    
    sess_1 = tf.Session(graph=Graph_1,config=config)
    sess_1.run(tf.global_variables_initializer())
    
print("area_1:",sess_1.run(area_1,feed_dict={height_1:100.,width_1:100.}))

area_1: Tensor("area:0", dtype=float32)
Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5

area_1: 10000.0
